# https://docs.python.org/3/library/unittest.html

# Setup: import packages, create dummy data.

import sys
sys.path.append('./')

import unittest, polars, numpy, shutil, os
from EnvironmentData import EnvironmentData

# dummy_table = polars.DataFrame([
#     {'SensorID': numpy.int32(1), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(1.1)},
#     {'SensorID': numpy.int32(2), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(2.2)},
#     {'SensorID': numpy.int32(3), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(3.3)},
#     {'SensorID': numpy.int32(4), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(4.4)},
#     {'SensorID': numpy.int32(5), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(5.5)},
# ])

# dummy_reading = {
#     'SensorID': numpy.int32(1),
#     'UTC': numpy.int64(1720542516),
#     'Reading': numpy.float32(1.1)
# }

# Define tests. 
class TestInitialization(unittest.TestCase):

    def data_exists(self):
        for key in envdt.readings:
            self.assertTrue(os.path.exists(f'test/data/{key}-testing.parquet'))
            self.assertTrue(polars.read_parquet(f'test/data/{key}-testing.parquet').shape[0] > 0)

    def logs_exist(self):
        self.assertTrue(os.path.exists('test/data/EnvironmentData.log'))

class TestGetReading(unittest.TestCase):

    def test_get_current_readings(self):

        envdt.get_current_readings()

        self.assertTrue(len(os.listdir('test/data/new-readings/')) > 0)

        new_files = {}
        for key in envdt.readings:
            new_files[key] = {'file': [x for x in os.listdir('test/data/new-readings/') if key in x][0]}
            new_files[key]['shape'] = polars.read_parquet(f'test/data/new-readings/{new_files[key]["file"]}').shape

        envdt.consolidate_readings()

        # The new-readings should be deleted after consolidation.
        self.assertTrue(len(os.listdir('test/data/new-readings/')) == 0)

        # Row could should increase by the number of rows in the new data.
        for key in envdt.readings:            
            self.assertTrue(new_files[key]['shape'][0] + shape_init[key][0] == polars.read_parquet(f'test/data/{key}-testing.parquet').shape[0])

if __name__ == '__main__':

    # Instantiate EnvironmentData class and capture initial shape.
    envdt = EnvironmentData(CatsUserID = 2496, data_path = 'test/data', testing = True)
    shape_init = {}
    for key in envdt.readings:
        shape_init[key] = polars.read_parquet(f'test/data/{key}-testing.parquet').shape

    # Run tests.
    unittest.main()

    # Delete data generated by tests.
    shutil.rmtree('test/data/')
