# https://docs.python.org/3/library/unittest.html

# Setup: import packages, create dummy data.

import sys
sys.path.append('./')

import unittest, polars, numpy, shutil, os
from EnvironmentData import EnvironmentData

# dummy_table = polars.DataFrame([
#     {'SensorID': numpy.int32(1), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(1.1)},
#     {'SensorID': numpy.int32(2), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(2.2)},
#     {'SensorID': numpy.int32(3), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(3.3)},
#     {'SensorID': numpy.int32(4), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(4.4)},
#     {'SensorID': numpy.int32(5), 'UTC': numpy.int64(1720542516), 'Reading': numpy.float32(5.5)},
# ])

# dummy_reading = {
#     'SensorID': numpy.int32(1),
#     'UTC': numpy.int64(1720542516),
#     'Reading': numpy.float32(1.1)
# }

# Define tests. 
class TestInitialization(unittest.TestCase):

    # Does the data exist (this will run after initialization).
    def data_exists(self):
        self.assertTrue(os.path.exists(f'test/data/sensors.parquet'))
        dt = polars.read_parquet(f'test/data/sensors.parquet')
        self.assertTrue(dt.shape[0] > 0)
        self.assertTrue(dt.columns == ['SensorID', 'SensorReadingUTC', 'SensorReadingF', 'SensorReadingRh'])

    # Does the log exist? 
    def logs_exist(self):
        self.assertTrue(os.path.exists('test/data/EnvironmentData.log'))

class TestGetReading(unittest.TestCase):

    def test_get_current_readings_consolidate(self):

        envdt.get_current_readings()

        # Verify the new reading got saved.
        self.assertTrue(len(os.listdir('test/data/new-readings/')) > 0)

        # Count the number of new rows in new-readings.
        new_rows = 0
        for file in os.listdir('test/data/new-readings/'):
            new_rows += polars.read_parquet(f'test/data/new-readings/{file}').shape[0]

        # Consolidate readings and verify we have the expected row count.
        envdt.consolidate_readings()

        # The new-readings should be deleted after consolidation.
        self.assertTrue(len(os.listdir('test/data/new-readings/')) == 0)

        # Row could should increase by the number of rows in the new data.
        dt = polars.read_parquet(f'test/data/sensors.parquet')
        self.assertTrue(dt.shape[0] == init_rows + new_rows)

        # Columns should have been added because the current readings have many more columns.
        self.assertTrue(dt.shape[1] > 10)

        # we should also have device data now. 
        dt = polars.read_parquet(f'test/data/devices.parquet')
        self.assertTrue(dt.columns == ['DeviceDevID', 'DeviceName', 'SensorReadingUTC', 'SensorReadingF', 'SensorReadingRh'])

def tearDownModule():

    # Delete data generated by tests.
    envdt.close()
    shutil.rmtree('test/data/')

if __name__ == '__main__':

    # Instantiate EnvironmentData class and capture initial shape.
    envdt = EnvironmentData(CatsUserID = 2496, data_path = 'test/data', out_of_scope = ['-80', 'Cryo tank', 'Water'], testing = True)
    init_rows = polars.read_parquet(f'test/data/sensors.parquet').shape[0]

    # Run tests.
    unittest.main()
